name: Trigger Workflow

on:
  repository_dispatch:
    types: [push-event]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: echo "Workflow triggered by repository dispatch event."
